Rake::TaskManager.record_task_metadata = true

task :default do
  sh "rake -T"
end

desc "1. prepare c libarary"
task :prepare_c_library do |task|
  puts task.full_comment
  Dir.chdir("c-hello") do
    sh "cmake ."
    sh "cmake --build ."
  end
end

desc "2. compile interop caller .java"
task :compile_java_caller do |task|
  puts task.full_comment
  Dir.chdir("java-native") do
    sh "javac hello/JNIHello.java"
  end
end

desc "3. generate interop java header"
task :generate_interop_header do |task|
  puts task.full_comment
  Dir.chdir("java-native") do
    sh "javah -d . hello.JNIHello"
  end
end

desc "4. copmile interop library"
task :compile_interop_library do |task|
  puts task.full_comment
  Dir.chdir("java-interop") do
    cp "../c-hello/include/hello.h", "include/hello.h"
    cp "../java-native/hello_JNIHello.h", "include/hello_JNIHello.h"
    sh "cmake ."
    sh "cmake --build ."
  end
end

desc "5. build clojure project"
task :build_clojure_project do |task|
  puts task.full_comment
  Dir.chdir("clj-hello") do
    if Gem.win_platform?
      cp "../c-hello/Debug/hello.dll", "."
      cp "../java-interop/Debug/hello_jni.dll", "."
      sh "boot build"
      sh "java -jar target\\clj-hello-0.1.0-SNAPSHOT-standalone.jar"
    else
      cp "../c-hello/libhello.so", "."
      cp "../java-interop/libhello_jni.so", "."
      sh "boot build"
      sh "LD_LIBRARY_PATH=`pwd` java -jar target/clj-hello-0.1.0-SNAPSHOT-standalone.jar"
    end
  end
end

desc "do all"
task :all => [:prepare_c_library, :compile_java_caller, :generate_interop_header, :compile_interop_library, :build_clojure_project] do |task|
  puts task.full_comment
end
