/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class hello_JNIHello */

#ifndef _Included_hello_JNIHello
#define _Included_hello_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     hello_JNIHello
 * Method:    Hello
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_hello_JNIHello_Hello
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
